# prometheus
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nb-green-ops-prometheus
  namespace: green-ops
spec:
  selector:
    matchLabels:
      app: nb-green-ops-prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: nb-green-ops-prometheus
    spec:
      containers:
        - name: prometheus
          image: 'prom/prometheus:latest'
          # command: 
          # - "/bin/prometheus"
          # - "--config.file=/etc/prometheus/prometheus.yml"
          # - "--storage.tsdb.path=/prometheus"
          # - "--storage.tsdb.retention.time=30d"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http-prometheus
              protocol: TCP
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 256Mi
          volumeMounts:
          - mountPath: /prometheus
            name: data
          - mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
            name: prometheus-yml

      volumes:
        - name: data
          emptyDir:
            sizeLimit: 16Gi
        - name: prometheus-yml
          configMap:
            name: prometheus-yml

